### ISSUE TITLE
Rize\UriTemplate::__construct(): Implicitly marking parameter $parser as nullable is deprecated, the explicit nullable type must be used instead

### ISSUE THREAD

**Issue by shyim** [rize/UriTemplate#29]
```
PHP Deprecated:  Rize\UriTemplate::__construct(): Implicitly marking parameter $parser as nullable is deprecated, the explicit nullable type must be used instead in /Users/shyim/Developer/sw-trunk/vendor/rize/uri-template/src/Rize/UriTemplate.php on line 20
```

**Comment by clue** [comment]
Thanks for looking into this! Let me try to clarify: I see this was originally fixed in #30 and then reverted in #32 to fix PHP compatibility issues reported in #31. Later, #33 updated the minimum PHP requirement and also addressed this issue as part of this changeset.

It's my understanding the compatibility issue should be fixed on the latest dev version, but there's currently no version available with these changes included. I see #31 and #33 contain some discussion about releasing a `0.4.0` with the BC break included which I agree would be the best way looking forward. May I ask if there is an ETA or anything else planned for `0.4.0` that we could help with or anything else that would currently block this release?

Technically, we may also implement the required changes in a way that is backwards compatible like we did in @ReactPHP (see e.g. https://github.com/clue/reactphp-docker/pull/88), but I'm not trying to suggest the extra effort would be worth it for every project. There's currently no separate v0.3/v0.4 release branch here, otherwise we may take a look at this and see if it's worth it. Either approach would work for me, so I'm all for whatever is required to get PHP 8.4 fully supported :+1:

**Comment by rezigned** [comment]
@clue Thanks for your suggestion. I think we could just release it as 0.4.0 (instead of 1.0.0) as everyone suggested.

**Comment by rezigned** [comment]
FYI: I'm preparing for 0.4.0 release #34 and here we go https://github.com/rize/UriTemplate/releases/tag/0.4.0
